### ISSUE TITLE
Request for gompertz_data

### ISSUE THREAD

**Issue by ghost** [tobydriscoll/fnc-extras#1]
Hi, 
In labs/chapter04/Gompertz mentioned we need "gompertz_data", however, I can't find the file everywhere. Could you please update to data folder or somewhere else? Thank you!

**Comment by tobydriscoll** [comment]
Resolved by d4997a13ab796b6444e341c371334bbed1c560a2. Sorry it took so long (and after a semester ended...)!

**Comment by RoyiAvital** [comment]
Is there a way to buy this in a PDF format outside the USA (Google Play won't work)?

**Comment by tobydriscoll** [comment]
I assume you mean the textbook. I will inquire with the publisher.

**Comment by tobydriscoll** [comment]
The publisher claims that the ebook should be available internationally via Google Play. If you have difficulties, please send them to me at driscoll@udel.edu.
