### ISSUE TITLE
Full text with Julia examples

### ISSUE THREAD

**Issue by Dale-Black** [tobydriscoll/fnc-extras#7]
Hello, is there a full text with the Julia notes implemented? I see the free website but I don’t see any place to go through the last half of the text with the Julia examples included. Please let me know if there is a way to get access to that, as I’d be more than happy to pay!

**Comment by tobydriscoll** [comment]
It's going to be officially published by SIAM in the coming months. In the meantime, there's a version at

http://tobydriscoll.net/fnc-julia/frontmatter.html

You can at least copy/paste the codes pretty easily from there. There are a few glitches in the presentation, but the content is all there.
